version: '3'

volumes:
  ppe_local_db:
  ppe_pgadmin:

services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  postgres:
    image: 'postgres:12-alpine'
    volumes:
      - 'ppe_local_db:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: 'trackppe'
      POSTGRES_PASSWORD: 'trackppe'
      PGDATA: '/var/lib/postgresql/data/pgdata'
      POSTGRES_DB: 'trackppe'

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: help@ppecovid.in
      PGADMIN_DEFAULT_PASSWORD: 'trackppe'
    volumes:
      - ppe_pgadmin:/var/lib/pgadmin

